/**
 * This file was automatically generated by the Mule Development Kit
 */
package com.espn.mule.connector.phantomjs;

import org.mule.api.annotations.Connector;
import org.mule.api.annotations.Connect;
import org.mule.api.annotations.ValidateConnection;
import org.mule.api.annotations.ConnectionIdentifier;
import org.mule.api.annotations.Disconnect;
import org.mule.api.annotations.param.ConnectionKey;
import org.mule.api.ConnectionException;
import org.mule.api.annotations.Configurable;
import org.mule.api.annotations.Processor;

import com.espn.phantomjs.PhantomJs;
import com.espn.phantomjs.client.*;

/**
 * Cloud Connector
 *
 * @author MuleSoft, Inc.
 */
@Connector(name="phantomjs", schemaVersion="1.0-SNAPSHOT")
public class PhantomJsConnector
{
    private PhantomJs phantomJsClient = new PhantomJs(new PhantomJsWebDriverClient("/usr/local/bin/phantomjs", 60));

    /**
     * screenshot
     *
     * {@sample.xml ../../../doc/PhantomJs-connector.xml.sample phantomjs:screenshot}
     * @param url String
     * @return image bytes
     * @throws Exception for url
     */
    @Processor
    public byte[] screenshot( String url ) throws Exception {
        return phantomJsClient.screenshot(url);
    }
}
